# Generated by Django 2.0.1 on 2018-03-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sysusers',
            fields=[
                ('user_id', models.FloatField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('hobby', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'SYSUSERS',
                'managed': False,
            },
        ),
    ]
