# Generated by Django 2.0.1 on 2018-03-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('movie_id', models.FloatField(primary_key=True, serialize=False)),
                ('imdb_id', models.FloatField(blank=True, null=True)),
                ('tmdb_id', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'LINKS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.FloatField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('genres', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=5, null=True)),
                ('genres_en', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'MOVIES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('user_id', models.FloatField(primary_key=True, serialize=False)),
                ('movie_id', models.FloatField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'RATINGS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.FloatField(blank=True, null=True)),
                ('movie_id', models.FloatField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'TAGS',
                'managed': False,
            },
        ),
    ]
