# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-05 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sysusers',
            fields=[
                ('user_id', models.FloatField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('hobby', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sysusers',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='links',
            table='links',
        ),
        migrations.AlterModelTable(
            name='movies',
            table='movies',
        ),
        migrations.AlterModelTable(
            name='ratings',
            table='ratings',
        ),
        migrations.AlterModelTable(
            name='tags',
            table='tags',
        ),
    ]
